@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
     
     

rankdir=LR

title[label="https://graphviz.org/doc/info/arrows.html" URL="https://graphviz.org/doc/info/arrows.html" shape=none]

here -> there [label=label]
head -> tail [taillabel=taillabel headlabel=headlabel]

arrowhead -> "[arrowhead=dot]" [arrowhead=dot]
arrowhead -> "[arrowhead=diamond]" [arrowhead=diamond]
arrowsize -> "[arrowsize=3]" [arrowsize=3]
arrowtail-> "[arrowtail=invempty]" [arrowhead="invempty"]
color -> "[dir=both color=red:blue]" [dir=both color="red:blue"]
style -> "[style=dashed]" [style=dashed]
color -> "[dir=none color=green:red;0.25:blue]" [dir=none color="green:red;0.25:blue"]

with -> {sets, of, stuff} -> {singletons}
in -> a -> pipeline
this -> that

}

@enduml
