@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

 rankdir=LR

 title[ shape=none
 label="https://graphviz.org/doc/info/colors.html"
 URL="https://graphviz.org/doc/info/colors.html"
]

default
"[color=red]" [color=red]
"[fontcolor=blue]" [fontcolor=blue]
"[style=filled color=red]" [style=filled color=red]

}

@enduml
