@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

 Server -> routes

 gateway -> json
 gateway -> meraki

 domain -> json
 domain -> meraki

 routes -> meraki
 routes -> domain

 exec   -> meraki
 linker -> json
 linker -> routes

subgraph cluster_gateway {
 color=red
 gateway [shape=plaintext]
 linker  [shape=plaintext]
 gateway -> linker
}

subgraph cluster3 {
 json -> "groovy.json"
}

subgraph cluster1 {
 domain -> {"java.time" , "groovy.transform" }
}

subgraph cluster2 {
 routes -> { gateway, exec }
}

subgraph cluster0 {
 meraki -> { json , http }
 http   -> "java.net"
}

subgraph cluster_key {
  package
  class [shape=plaintext]
}

}

@enduml
