@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

Server -> routes

gateway -> json
gateway -> meraki

domain -> json
domain -> meraki
routes -> meraki
routes -> domain

subgraph cluster3 {
 json -> "groovy.json"
}

subgraph cluster1 {
 domain -> "java.time"
 domain -> "groovy.transform"
}

subgraph cluster2 {
routes  -> gateway -> routes [color=red]
gateway [color=red]
}

subgraph cluster0 {
 meraki -> json
 meraki -> http
 http   -> "java.net"
}

}

@enduml
