@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

 Practical [fontsize=40 shape=star style=filled color=yellow]

 Iterative    -> Practical
 Quick        -> Practical
 Automated    -> Practical
 Maintainable -> Practical
 Text         -> Practical
}

@enduml
