@startuml
digraph G {

rankdir=LR

subgraph cluster_6 {
  label = "unbox"
  style="invis"
  box -> potatos
  box -> scallions
  box -> carrots
  box -> apple
  box -> pork
  box -> "C&P"
  box -> jam
  box -> mayonnaise
  box -> vinegar
}


"S&P 1" -> "rubbed pork"
"S&P 3" -> "mashed potatos"
"S&P 4" -> "slaw bowl"
"S&P 2" -> "microwaved sauce"

"C&P" -> "1/4 tsp C&P"
"C&P" -> "remaining C&P"
vinegar -> "4 tsp vinegar"
vinegar -> "remaining vinegar"
"1/4 tsp C&P" -> "rubbed pork"
pork -> "rubbed pork"
oil -> "rubbed pork"

mayonnaise -> "slaw bowl"

water -> "pot of water"
salt -> "pot of water"

"2Tbsp butter" -> "mashed potatos"
"1Tbsp butter" -> "microwaved sauce"

subgraph cluster_5 {
  label = "chop"
  style=filled
  color=tan
  node [style=filled,color=white]
  scallions -> "sliced scallions"
  carrots -> "grated carrots"
  apple -> "sliced apple"
  potatos -> "diced potatos"
}

subgraph cluster_0 {˝
  label = "pork (20 minutes)"
  style=filled
  color=tan
  fontsize=30
  node [style=filled,color=white]
  "rubbed pork" -> "baking sheet" -> "450°F oven" -> "18-20 minutes" -> "roasted pork" -> "sliced pork"
}

subgraph cluster_1 {
  label = "slaw"
  style=filled
  color=pink
  node [style=filled,color=white]
  "sliced apple" -> "slaw bowl"
  "sliced scallions" -> "slaw bowl"
  "grated carrots" -> "slaw bowl"
  "4 tsp vinegar" -> "slaw bowl"
  "slaw bowl" -> slaw
}

subgraph cluster_2 {
  label = "mashed potatos (25 minutes)"
  style=filled
  color=lightgray
  fontsize=30
  node [style=filled,color=white]
  "diced potatos" ->"pot of water" -> "bring to boil" -> "15-20 minutes" -> drain -> mash -> "mashed potatos"
  "sliced scallions" -> "mashed potatos"
}

subgraph cluster_3 {
  label = "sauce (1 minute)"
  style=filled
  color=pink
  fontsize=30
  node [style=filled,color=white]
  "remaining vinegar" -> "sauce bowl"
  "remaining C&P"-> "sauce bowl"
  jam -> "sauce bowl" -> microwave -> "45 seconds" -> "microwaved sauce"
}

subgraph cluster_4 {
  style=invis
  "mashed potatos" -> plate
  "microwaved sauce" -> plate
  "sliced pork" -> plate
  slaw -> plate
}


apple [style=filled fillcolor=red]
"sliced apple" [style=filled fillcolor=red]
box [shape=box style=filled fillcolor=tan]
"450°F oven" [shape=box]
microwave [shape=box]
mash [shape=star]
"baking sheet" [shape=box style=filled fillcolor=gray]
plate [shape=doublecircle]
"pot of water" [shape=cylinder style=filled fillcolor=gray]
"mashed potatos" [shape=cylinder style=filled fillcolor=gray]
"slaw bowl" [shape=invtrapezium style=filled fillcolor=orange]
"sauce bowl" [shape=invtrapezium style=filled fillcolor=red]
"microwaved sauce" [shape=invtrapezium style=filled fillcolor=red]
scallions [style=filled fillcolor=darkgreen]
"sliced scallions" [style=filled fillcolor=darkgreen]
carrots [style=filled fillcolor=orange]
"grated carrots" [style=filled fillcolor=orange]
"slaw" [style=filled fillcolor=orange]
"1Tbsp butter" [shape=box style=filled fillcolor=yellow]
"2Tbsp butter" [shape=box style=filled fillcolor=yellow]
pork [style=filled fillcolor=brown]
"rubbed pork" [style=filled fillcolor=brown]
"roasted pork" [style=filled fillcolor=brown]
"sliced pork" [style=filled fillcolor=brown]
potatos [style=filled fillcolor=brown]
"diced potatos" [style=filled fillcolor=brown]
water [style=filled fillcolor=lightblue]
jam [shape=cylinder style=filled fillcolor=red]
vinegar [shape=cylinder]
"4 tsp vinegar" [shape=cylinder style=filled fillcolor=white]
"remaining vinegar" [shape=cylinder style=filled fillcolor=white]
"C&P" [style=filled shape=trapezium fillcolor=brown]
"remaining C&P" [style=filled shape=trapezium fillcolor=brown]
"1/4 tsp C&P" [style=filled shape=trapezium fillcolor=brown]
"S&P 1" [shape=trapezium style=filled fillcolor=gray]
"S&P 2" [shape=trapezium style=filled fillcolor=gray]
"S&P 3" [shape=trapezium style=filled fillcolor=gray]
"S&P 4" [shape=trapezium style=filled fillcolor=gray]
salt [shape=trapezium]

}
@enduml
