@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

 rankdir=LR

 title[shape=none fontcolor=blue
 label="http://graphviz.org/doc/info/shapes.html"
 URL="http://graphviz.org/doc/info/shapes.html"
 ]

 label = "[shape=?]"
 box          [shape=box]
 circle       [shape=circle]
 doublecircle [shape=doublecircle]
 cylinder     [shape=cylinder]
 folder       [shape=folder]

}

@enduml
