@startuml
digraph G {
     bgcolor="transparent"
     node[style=filled color=white]
     

Java -> "C#" -> {Java, "Objective C"}
Java -> "Objective C" -> Swift -> Java
Java -> Groovy
JavaScript -> Groovy
Groovy -> JavaScript -> Go
Go -> TypeScript -> "C#" -> Scala

  "My Recent Primary Languages" [shape=none fontsize=20]
}

@enduml
