@startuml
digraph G {
     
  bgcolor="transparent"
  node[style=filled color=white]
  edge[color=white]
     
     

# Which way does sync go?
Hana -> Sync -> Kafka
#Kafka-> Sync -> Hana

# It's clearer to me left to right
rankdir=LR

# Hana is a database
Hana [shape=cylinder]

# Sync is an app
Sync [shape = box]

# Sync, does that, but Oracle is the preferred database, now
Hana [style=filled color=gray] Oracle [shape=cylinder]

# Also, the Oracle connection is a critical read/write connection.
Oracle -> Sync [dir=both color=red label=critical]

# And Kafka is hosted offsite in AWS
subgraph cluster_AWS { label = "AWS" style=filled color=tan fontsize=30 Kafka }

# Actually, the details of Sync are configured by Vault
Vault[shape=box3d] Vault -> Sync [taillabel=config style=dotted]

# We should give this a title
"Sync Flow"[shape=none fontsize=40]

# Can you email this to me?
URL[shape=none URL="https://dreampuf.github.io/GraphvizOnline/?url=https://raw.githubusercontent.com/curtcox/practical-graphviz/master/dot/whiteboard.dot"]
}

@enduml
