@startuml
digraph G {
     bgcolor="transparent"
     node[style=filled color=white]
     

rankdir=LR

files -> pipeline -> editor -> graphviz -> output [color=blue arrowsize=4 arrowhead=vee]

before [shape=none label=""]
after [shape=none label=""]
before->after [label="and then" fontsize=30 color=blue arrowsize=4 arrowhead=vee]

{ "C#" Scala, Dart, Go, Java, Groovy, "Objective C"} -> files
{ grep, sed, awk, groovy} -> pipeline
{ vi, Atom, VSCode, online, xdot, IntelliJ } ->editor
{ PDF, PNG, SVG } -> output

 member [shape=none label=""]
 set [shape=none label=""]
 member->set [label="for instance" fontsize=30]

 subgraph cluster_languages {
   style="invis"
   "C#" [shape=none]
   "Scala" [shape=none]
   "Dart" [shape=none]
   "Go" [shape=none]
   "Java" [shape=none]
   "Groovy" [shape=none]
   "Objective C" [shape=none]
   files [shape=folder fontsize=30]
 }

 subgraph cluster_pipeline {
   style="invis"
   grep [shape=none]
    awk [shape=none]
    sed [shape=none]
   groovy [shape=none]
   pipeline [shape=rarrow fontsize=30]
 }

subgraph cluster_editor {
 style="invis"
 IntelliJ [shape=none]
 Atom     [shape=none]
 VSCode   [shape=none]
 vi       [shape=none]
 online   [shape=none]
 xdot     [shape=none]
 editor   [shape=box fontsize=30]
}

 subgraph cluster_output {
   style="invis"
   PDF [shape=none]
   PNG [shape=none]
   SVG [shape=none]
   output [shape=star style=filled color=yellow fontsize=30]
 }

 tldr -> graphviz
 tldr [shape=none fontsize=20 label="dot -Tpng -O path/to/file.dot"]
 graphviz [fontsize=30 style=filled color=blue fontcolor=white]

 "Typical Workflow
 "[shape=none fontsize=40]

}

@enduml
